# Site settings
title: Chathura Prabashana
description: DevOps Enthusiast & IT Undergraduate
url: "https://PrabashanaDev.github.io"
theme: hacker

# Navigation (optional)
# These links will appear in the top menu
# Page names should match your markdown files (without the .md extension)
header_pages:
  - index.md
  - about.md
  - projects.md
